---
title: "wk5_prac"
author: "Leandra"
date: "11/4/2021"
output: html_document
---

```{r load libraries}
library(sf)
library(tmap)
# library(tmaptools)
library(tidyverse)
library(here)
library(janitor)
```

```{r borough and ward data}
# London Borough data is already in British National Grid
# but not 27700
# if we don't transform to 27700, we will get an error when we join with the Airbnb data later
# error: st_crs(x) == st_crs(y) is not TRUE
Londonboroughs <- st_read(here::here("data",
                                     "statistical-gis-boundaries-london",
                                     "ESRI",
                                     "London_Borough_Excluding_MHW.shp")) %>%
  clean_names() %>%
  st_transform(., 27700)

Londonwards <- st_read(here::here("data",
                                  "statistical-gis-boundaries-london", 
                                  "ESRI", 
                                  "London_Ward_CityMerged.shp")) %>%
                        clean_names()
# st_transform(., 27700)
```

```{r hotel & airbnb data}
# multipolygon data in WGS84
OSM <- st_read(here::here("data",
                          "greater-london-latest-free", 
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700)

Airbnb <- read_csv("data/listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), 
           crs = 4326) %>%
  st_transform(., 27700)%>%
  clean_names()

ward_bedrooms <- read_csv("data/bulk.csv") %>%
  clean_names()
```

```{r other data for plotting the map}
# Original CRS is WGS84
# Transform to 27700
UK_outline <- st_read(here::here("data",
                                "gadm36_GBR_shp", 
                                "gadm36_GBR_0.shp")) %>%
  st_transform(., 27700)

# st_crs(UK_outline)

Worldcities <- st_read(here::here("data", 
                                  "World_Cities", 
                                  "World_Cities.shp"))
# point data
# don't transform here as it is a global dataset
# select the cities you want then transform to British National Grid

```

```{r number of bedrooms per borough}
# one borough is made up of many wards
# first join ward bedroom csv data w the wards
# Londonwards data has info on which borough the ward belongs to
# group by borough
beds_borough <- Londonwards %>%
  left_join(.,
            ward_bedrooms,
            by = c("gss_code" = "geography_code")) %>%
  group_by(lb_gss_cd) %>%
  summarise(total_beds_per_borough=sum(bedrooms_all_categories_number_of_bedrooms_measures_value)) %>%
  st_drop_geometry()
# drop_geometry so that we can join with the London Borough data later
```

```{r airbnb per borough}
airbnb_borough <- Airbnb %>%
  # select entire places that are available all year
  filter(room_type == 'Entire home/apt' & availability_365 =='365') %>%
  # by default, join will use st_intersects
  # refer to http://postgis.net/workshops/postgis-intro/spatial_relationships.html for more info on spatial relationships
  st_join(Londonboroughs, .) %>%
  group_by(gss_code) %>%
  summarise(airbnbcount = n()) %>%
  st_drop_geometry()
# drop_geometry so that we can join with the London Borough data later
  
# alternative way
# dplyr::count is a quick way of doing group_by and summarise as above
airbnb_borough2 <- Airbnb %>%
  filter(room_type == 'Entire home/apt' & availability_365 =='365') %>%
  st_join(Londonboroughs,.) %>%
  count(gss_code, name="airbnbcount")

# add_count adds a column to the dataset but keeps the same number of rows
# so we end up with 970 obs of 25 variables if we do this
airbnb_borough3 <- Airbnb %>%
  filter(room_type == 'Entire home/apt' & availability_365 =='365') %>%
  st_join(Londonboroughs,.) %>%
  add_count(gss_code, name="airbnbcount")
# note: can change the wt (weight) argument to compute the sum(weight) for each group
```

```{r hotels per borough}
hotels_borough <- OSM %>%
  filter(fclass == 'hotel') %>%
  st_join(Londonboroughs, .) %>%
  count(gss_code, name="hotelcount") %>%
  st_drop_geometry()
# drop_geometry so that we can join with the London Borough data later
```

```{r join all data together}
all_data_one <- Londonboroughs %>%
  left_join(.,
            beds_borough,
            by = c("gss_code" = "lb_gss_cd"))

all_data_two <- all_data_one %>%
  left_join(.,
            airbnb_borough,
            by = c("gss_code" = "gss_code"))

all_data_three <- all_data_two %>%
  left_join(., 
            hotels_borough, 
            by = c("gss_code" = "gss_code"))

```

```{r normalise by total beds per borough}
mapnorm <- all_data_three %>%
  mutate(airbnbnorm=airbnbcount/total_beds_per_borough)%>%
  mutate(hotelnorm=hotelcount/total_beds_per_borough)
```

```{r extract 3 cities}
Worldcities_extract <- Worldcities %>%
  filter(CITY_NAME == "Edinburgh" | 
          CITY_NAME == "Birmingham" |
           CITY_NAME == "London")
# st_transform(., 27700)
```

```{r plot the maps}
tmap_mode("plot")

airbnb_map <- tm_shape(mapnorm) + 
  tm_polygons("airbnbnorm", 
              style="jenks",
              palette="PuBu") +
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)

hotel_map <- tm_shape(mapnorm) + 
  tm_polygons("hotelnorm",
              style="jenks", 
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

# qtm(UK_outline)
# run this and you will see that the map is not centred on the UK because of some outlying islands
# hence the need to set the new bbox

# UK_outline$geometry
# run this to see the current bbox

# new bbox we set is not much different from UK_outline$geometry
newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)

UK_outlinecrop <- UK_outline$geometry %>%
  st_crop(., newbb)

UK_map <- tm_shape(UK_outlinecrop) + 
  # fill colour of the map
  tm_polygons(col="darkslategray1") +
  tm_layout(frame=FALSE) +
  tm_shape(Worldcities_extract) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)

legend <- tm_shape(mapnorm) +
  tm_fill("hotelnorm",
          title="Accommodation count", 
          style="jenks", 
          palette="PuBu") +
  tm_scale_bar(position=c(0.2,0.04), 
               text.size=0.6) +
  tm_compass(north=0, 
             position=c(0.65,0.6)) +
  tm_layout(legend.only = TRUE, 
            legend.position = c(0.2,0.25), 
            asp = 0.1) +
  tm_credits("(c) OpenStreetMap contributors and Airbnb",
             position=c(0.0,0.0))

final = tmap_arrange(airbnb_map, hotel_map, UK_map, legend, ncol=2)

# tmap_save(final, 'hotelsandairbnbR.png')
```

```{r alternative way to arrange map}
library(grid)
grid.newpage()

pushViewport(viewport(layout=grid.layout(2,2)))
print(airbnb_map, vp=viewport(layout.pos.col=1, layout.pos.row=1, height=5))
print(hotel_map, vp=viewport(layout.pos.col=2, layout.pos.row=1, height=5))
print(UK_map, vp=viewport(layout.pos.col=1, layout.pos.row=2, height=5))
print(legend, vp=viewport(layout.pos.col=2, layout.pos.row=2, height=5))
```
```{r inset map}
Londonbb = st_bbox(mapnorm) %>% 
  st_as_sfc()

main <- tm_shape(mapnorm, bbox=Londonbb) +
  tm_polygons("airbnbnorm", 
              style="jenks", 
              palette="PuBu") +
  tm_scale_bar(position = c("left", "bottom"), text.size = .75) +
  tm_layout(legend.position = c("right","top"),
            legend.text.size=.65, 
            legend.title.size = 1.1,
            frame=FALSE) +
  tm_credits("(c) OpenStreetMap contributors and Airbnb",
             position=c(0.0,0.0)) +
  tm_compass(type = "8star", position = c(0.06, 0.1)) +
  tm_layout(inner.margins=c(0.02,0.02,0.02,0.2))
  # vector: bottom, left, top, and right margin values

inset <- tm_shape(UK_outlinecrop) +
  tm_polygons(col="darkslategray1", lwd=1) +
  tm_shape(Londonbb) +
  tm_borders(col="grey40", lwd = 3) +
  tm_layout(frame=FALSE, bg.color="transparent") +
  tm_shape(Worldcities_extract) +
  tm_symbols(col = "red", scale = .5) +
  tm_text("CITY_NAME", xmod=-1.5, ymod=-0.5)

print(inset, vp = viewport(0.86, 0.29, width = 0.5, height = 0.55))

# tmap_save(main,insets_tm = inset,insets_vp=viewport(x=0.86, y=0.29, width=.5, height=.55), filename="test.pdf", dpi=600)
```

